# Generated by Django 5.0.3 on 2024-03-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_rename_users_messages_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
