# Generated by Django 5.0.3 on 2024-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_remove_message_message_time_message_time_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sent_at',
            field=models.DateTimeField(),
        ),
    ]
