# Generated by Django 5.0.3 on 2024-03-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_rename_messages_message_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='uuser',
        ),
    ]
